version: '3.8'

services:

  # BANCO DE DADOS
  mysql:
    image: mysql
    container_name: overhands-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - ntwk

  phpmyadmin:
    image: phpmyadmin
    container_name: overhands-phpmyadmin
    ports:
      - 8080:80
    networks:
      - ntwk
    environment:
      - PMA_ARBITRARY=1

  minio: 
          image: minio/minio
          container_name: overhands-minio
          environment:
              MINIO_ROOT_USER: samuel
              MINIO_ROOT_PASSWORD: samuel123
          volumes:
              - minio_data:/data
          ports:
              - 9000:9000
              - 9001:9001
          command: server --console-address ":9001" /data

networks:
  ntwk:

volumes:
    minio_data: