version: '3.8'

services:

  # BANCO DE DADOS
  mysql:
    image: mysql
    container_name: overhands-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - ntwk

  phpmyadmin:
    image: phpmyadmin
    container_name: overhands-phpmyadmin
    ports:
      - 8080:80
    networks:
      - ntwk
    environment:
      - PMA_ARBITRARY=1


networks:
  ntwk:
